### ISSUE TITLE
Like the idea, but I may be dumb..

### ISSUE THREAD

**Issue by ghost** [JordanChoo/sitemap-generator#3]
This is what I have for code

require 'sitemap.php';

 $SitemapNode = new Sitemap('SitemapFolder', 'NameOfSitemap');

```
$config = array(
        'type'   => 'url',
        'params' => array(
                'loc'      => 'http://example.com',
                'freq'     => 'daily',
                'priority' => '0.5',
            ),
    );

$SitemapNode->add_node($config);   
```

and it tell me that sitemap class not found? Im sure im doing something wrong, and youll shake your head, but could you please help me?

Thanks

**Comment by JordanChoo** [comment]
Actually, it is something on my end! I didn't implement Namespace properly. If you just go to line 10 and comment out:

``` php
namespace SitemapGenerator;
```

It should fix the problem. I've already updated the repo to fix the problem so you could just do a git pull if that works better for you. 

Let me know if it works and if you run into any more bugs =).

**Comment by ghost** [comment]
That worked, this class is beautiful and works perfectly for what I need. Thanks for the quick fix. If their is anything I could reciprocate from my codecanyon portfolio feel free to ask. 

http://codecanyon.net/user/groupp/portfolio
